### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by devasmith** [negasus/haproxy-spoe-go#18]
Hi. We are using [coraza-spoa](https://github.com/corazawaf/coraza-spoa) which is using this library. Notices that this service is gradually increasing it's memory usage. This service is now enabled on a site that has a lot of incoming requests to process.

Took out a [pprof](https://github.com/google/pprof) file and a graph of the memory consumption.

![profile001](https://github.com/negasus/haproxy-spoe-go/assets/60352859/ed8b364b-87d7-44db-bf60-f965d793bb53)
![Screenshot 2023-10-09 at 08 40 52](https://github.com/negasus/haproxy-spoe-go/assets/60352859/0aff6aa5-9e39-457d-83a1-0c1181b9cb30)

Together with this memory usage we notice this:
`level=warning msg="spoe: error handling connection: disconnect error: I/O error"` 

Not sure if this is connected to haproxy-spoe-go or something else but that causes a lot of the requests to not be processed correctly (Failed to parse request body).

Any clue on how we can troubleshoot this further?

**Comment by negasus** [comment]
I will try to investigate this issue and returns later

**Comment by negasus** [comment]
Judging by the picture, this code from https://github.com/criteo/haproxy-spoe-go library. But I found some porential leaks in my library) thanks. It will fixed soon

**Comment by 15ljindal** [comment]
Filed https://github.com/criteo/haproxy-spoe-go/issues/39 as I ran into the same issue with https://github.com/criteo/haproxy-spoe-go
