### ISSUE TITLE
No ip_score returned

### ISSUE THREAD

**Issue by UnveilTech** [negasus/haproxy-spoe-go#19]
Hello,

we're facing something weird, here is the haproxy part:
...
http-request capture var(sess.myiprep.ip_score) len 3
http-response set-header X-IP-Score "%[var(sess.myiprep.ip_score)]"
...

in the Go file, "ip_score" is correct (verified with a dedicated log file) but it seems not properly sent back to Haproxy by "req.Actions.SetVar(action.ScopeSession, "ip_score", ipScore)"

**here is the iprep.conf:**
[ip-reputation]
spoe-agent iprep-agent
	messages check-client-ip
	option var-prefix myiprep
	option continue-on-error
	timeout hello 2s
	timeout idle  2m
	timeout processing 10ms
	use-backend agents
	no log
spoe-message check-client-ip
	args ip=src
	event on-client-session if ! { src -f /etc/haproxy/whitelist.lst }

any idea ?

bye Fred

**Comment by UnveilTech** [comment]
Hi,
bug from our side...

**Comment by negasus** [comment]
Can I close this issue?
