### ISSUE TITLE
ack frame write failed

### ISSUE THREAD

**Issue by LaurenceJJones** [negasus/haproxy-spoe-go#21]
Hey under heavy load on the server seems after sometime to spoa server cannot write to the connection as haproxy has closed it? Do you have any pointers or information on where I can look to debug this?

```
spoa-1      | time="2024-05-15T18:24:46Z" level=error msg="ack frame write failed: cannot write frame to connection: write tcp 10.5.5.254:9000->10.5.5.4:38230: use of closed network connection" worker=spoa1
```

Thank you for spending time on writing this package 👍🏻

**Comment by LaurenceJJones** [comment]
Okay, nevermind some reason it now working 🤷🏻 I removed a haproxy config for timeout wasnt a problem before sorry for wasting time

**Comment by Infusible** [comment]
@LaurenceJJones how do you fix this errors?
